# Spring properties
spring:
  application:
     name: users-service

  jpa:
      database: MYSQL
      hibernate:
        ddl-auto: update
  datasource:
    platform: mysql

# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/

# HTTP Server
server:
  port: 2222   # HTTP (Tomcat) port